menu = ["Code Assistant",
        "QnA",
        "Language Translator",
        "Search Engine",
        "Game Player",
        "Knowledge Provider",
        "Text Summarizer",
        "Conversation Bot",
        "Creative Writer",
        "Education Tutor",
        "Recipe Creator",
        "Travel Advisor",
        "Fitness Guide",
        "Nutrition Advisor",
        "Mental Health Helper",
        "Business Advisor",
        "Marketing Creator",
        "Styling Advisor",
        "Product Describer",
        "Resume Builder",
        "Interview Coach",
        "Medical Informer",
        "Legal Informer",
        "Science Explainer",
        "History Informer",
        "Philosophy Discussant",
        "Art Describer",
        "Music Educator",
        "Recommendation Bot",
        "Poetry and Song Writer",
        "Humor Generator",
        "Astrology Informer",
        "Dream Interpreter",
        "Meditation Guide",
        "Language Tutor",
        "Correspondence Helper",
        "News Summarizer",
        "Tech Supporter",
        "Event Planner",
        "Gardening Advisor",
        "Pet Care Advisor",
        "Parenting Advisor",
        "DIY Ideas",
        "Home Decorator",
        "Real Estate Advisor",
        "Financial Advisor",
        "Stock Informer",
        "Crypto Informer",
        "Game Strategist",
        "Board Game Explainer",
        "Sports Analyst",
        "Fitness Planner",
        "Yoga Guide",
        "Relaxation Guide",
        "Study Advisor",
        "Time Manager",
        "Goal Setter",
        "Motivation Speaker",
        "Language Practitioner",
        "Essay Helper",
        "Speech Writer",
        "Lecture Summarizer",
        "Research Assistant",
        "Experiment Ideator",
        "Math Solver",
        "Physics Explainer",
        "Chemistry Helper",
        "Biology Informer",
        "Geography Informer",
        "Astronomy Informer",
        "Environmental Educator",
        "Literature Analyst",
        "Poetry Analyst",
        "Art Critic",
        "Music Appreciator",
        "Film Analyst",
        "Theater Educator",
        "Dance Describer",
        "Magic Explainer",
        "Craft Creator",
        "Cooking Guide",
        "Beverage Informer",
        "Restaurant Recommender",
        "Virtual Assistant",
        "Scheduler",
        "Email Manager",
        "Social Media Advisor",
        "SEO Advisor",
        "Web Developer",
        "Graphic Designer",
        "Photography Guide",
        "Video Producer",
        "Podcast Advisor",
        "Voice Actor",
        "Instrument Tutor",
        "Singing Coach",
        "Conversation Partner",
        "Accent Coach",
        "Public Speaking Coach",
        "Conflict Resolver",
        "Career Counselor",
        "Life Coach",
        ]
